<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use RonasIT\Support\AutoDoc\Http\Middleware\AutoDocMiddleware;
use RonasIT\Support\AutoDoc\Services\SwaggerService;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->docService = app(SwaggerService::class);
    }

    public function tearDown()
    {
        $currentTestCount = $this->getTestResultObject()->count();
        $allTestCount = $this->getTestResultObject()->topTestSuite()->count();

        if (($currentTestCount == $allTestCount) && (!$this->hasFailed())) {
            $this->docService->saveProductionData();
        }

        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function skipDocumentationCollecting() {
        AutoDocMiddleware::$skipped = true;
    }
}
